export interface ProductCsvRow {
  'Type': 'variable';
  'SKU': string;
  'Name': string;
  'Published': 1;
  'Is featured?': '';
  'Visibility in catalog': 'visible';
  'Short description': '';
  'Description': string;
  'Date sale price starts': '';
  'Date sale price ends': '';
  'Tax status': 'taxable';
  'Tax class': '';
  'In stock?': 1;
  'Stock': '1000';
  'Backorders allowed?': 1;
  'Sold individually?': 0;
  'Weight (lbs)': '';
  'Length (in)': '';
  'Width (in)': '';
  'Height (in)': '';
  'Allow customer reviews?': 1;
  'Purchase note': '';
  'Sale price': string;
  'Regular price': string;
  'Categories': string;
  'Tags': '';
  'Shipping class': string;
  'Images': string;
  'Download limit': '';
  'Download expiry days': '';
  'Parent': '';
  'Grouped products': '';
  'Upsells': '';
  'Cross-sells': '';
  'External URL': '';
  'Button text': '';
  'Position': '';
  'Attribute 1 name': string;
  'Attribute 1 value(s)': string;
  'Attribute 1 visible': string;
  'Attribute 1 global': string;
  'Attribute 2 name': string;
  'Attribute 2 value(s)': string;
  'Attribute 2 visible': string;
  'Attribute 2 global': string;
  'Attribute 3 name': string;
  'Attribute 3 value(s)': string;
  'Attribute 3 visible': string;
  'Attribute 3 global': string;
  'zcp': string;
  'Sub_sku': string;
  'Rec': 1;
  'URL': string;
}
